default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: tps_development
  host: localhost
  username: tps_development
  password: tps_development

test:
  <<: *default
  database: tps_test
  host: localhost
  username: tps_test
  password: tps_test

production:
  <<: *default
  database: <%= ENV["POSTGRESQL_ADDON_DB"] %>
  host: <%= ENV["POSTGRESQL_ADDON_HOST"] %>
  username: <%= ENV["POSTGRESQL_ADDON_USER"] %>
  password: <%= ENV["POSTGRESQL_ADDON_PASSWORD"] %>
  port: <%= ENV["POSTGRESQL_ADDON_PORT"] %>
